# -*- coding: utf-8 -*-
"""sentimental_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpJjV4jeVhwSIP7cJ14nRVudUY6Ertpx
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from textblob import TextBlob
from wordcloud import WordCloud

df = pd.read_csv('/content/vaccinaation_tweets.csv')
df.head()

df.info()

df.isnull().sum()

df.columns

text_df = df.drop(['id', 'user_name', 'user_location', 'user_description', 'user_created',
       'user_followers', 'user_friends', 'user_favourites', 'user_verified',
       'date', 'hashtags', 'source', 'retweets', 'favorites',
       'is_retweet'], axis=1)
text_df.head()

text_df = text_df.drop_duplicates('text')

def polarity(text):
    return TextBlob(text).sentiment.polarity

text_df['polarity'] = text_df['text'].apply(polarity)
text_df.head(50)

def sentiment(label):
    if label <0:
        return "Negative"
    elif label ==0:
        return "Neutral"
    elif label>0:
        return "Positive"
text_df['sentiment'] = text_df['polarity'].apply(sentiment)
text_df.head()

fig = plt.figure(figsize=(5,5))
sns.countplot(x='sentiment', data = text_df)

pos_tweets = text_df[text_df.sentiment == 'Positive']
pos_tweets = pos_tweets.sort_values(['polarity'], ascending= False)
pos_tweets.head(50)

neg_tweets = text_df[text_df.sentiment == 'Negative']
neg_tweets = neg_tweets.sort_values(['polarity'], ascending= False)
neg_tweets.head(50)

neutral_tweets = text_df[text_df.sentiment == 'Neutral']
neutral_tweets = neutral_tweets.sort_values(['polarity'], ascending= False)
neutral_tweets.head(50)

text1 = ' '.join([word for word in pos_tweets['text']])
plt.figure(figsize=(10,10), facecolor='None')
wordcloud = WordCloud(max_words=500, width=1600, height=300,prefer_horizontal=1,min_word_length=5
                      ,color_func=lambda *args,**kwargs:"white").generate(text1)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('Most frequent words in positive tweets', fontsize=19)
plt.show()

text1 = ' '.join([word for word in neg_tweets['text']])
plt.figure(figsize=(10,10), facecolor='None')
wordcloud = WordCloud(max_words=500, width=1600, height=300,prefer_horizontal=1,min_word_length=5
                      ,color_func=lambda *args,**kwargs:"white").generate(text1)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('Most frequent words in negative tweets', fontsize=19)
plt.show()

text1 = ' '.join([word for word in neutral_tweets['text']])
plt.figure(figsize=(10,10), facecolor='None')
wordcloud = WordCloud(max_words=500, width=1600, height=300,prefer_horizontal=1,min_word_length=5
                      ,color_func=lambda *args,**kwargs:"white").generate(text1)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('Most frequent words in neutral tweets', fontsize=19)
plt.show()